Name:           ros-melodic-yujin-ocs
Version:        0.8.2
Release:        0%{?dist}
Summary:        ROS yujin_ocs package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/yujin_ocs
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-yocs-cmd-vel-mux
Requires:       ros-melodic-yocs-controllers
Requires:       ros-melodic-yocs-diff-drive-pose-controller
Requires:       ros-melodic-yocs-joyop
Requires:       ros-melodic-yocs-keyop
Requires:       ros-melodic-yocs-math-toolkit
Requires:       ros-melodic-yocs-rapps
Requires:       ros-melodic-yocs-safety-controller
Requires:       ros-melodic-yocs-velocity-smoother
Requires:       ros-melodic-yocs-virtual-sensor
Requires:       ros-melodic-yocs-waypoints-navi
BuildRequires:  ros-melodic-catkin

%description
Yujin Robot's open-source control software

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Jan 21 2019 Jihoon Lee <jihoonl@yujinrobot.com> - 0.8.2-0
- Autogenerated by Bloom

