Name:           ros-melodic-yocs-math-toolkit
Version:        0.8.2
Release:        0%{?dist}
Summary:        ROS yocs_math_toolkit package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/yocs_math_toolkit
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-ecl-build
Requires:       ros-melodic-ecl-config
Requires:       ros-melodic-ecl-exceptions
Requires:       ros-melodic-ecl-formatters
Requires:       ros-melodic-ecl-linear-algebra
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-tf
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-ecl-build
BuildRequires:  ros-melodic-ecl-config
BuildRequires:  ros-melodic-ecl-exceptions
BuildRequires:  ros-melodic-ecl-formatters
BuildRequires:  ros-melodic-ecl-linear-algebra
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-tf

%description
Math toolkit for Yujin open control system. This package is intended to contain
common use functions, mostly for simple mathematics but also for tf-related
conversions. By no means it pretends to be an efficient and robust, widely used
math library, but a play ground where to put common code that is typically
repeated in many robot control programs.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Jan 21 2019 Jihoon Lee <jihoonl@yujinrobot.com> - 0.8.2-0
- Autogenerated by Bloom

