Name:           ros-kinetic-yujin-ocs
Version:        0.8.1
Release:        0%{?dist}
Summary:        ROS yujin_ocs package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/yujin_ocs
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-yocs-cmd-vel-mux
Requires:       ros-kinetic-yocs-controllers
Requires:       ros-kinetic-yocs-diff-drive-pose-controller
Requires:       ros-kinetic-yocs-joyop
Requires:       ros-kinetic-yocs-keyop
Requires:       ros-kinetic-yocs-math-toolkit
Requires:       ros-kinetic-yocs-rapps
Requires:       ros-kinetic-yocs-safety-controller
Requires:       ros-kinetic-yocs-velocity-smoother
Requires:       ros-kinetic-yocs-virtual-sensor
Requires:       ros-kinetic-yocs-waypoints-navi
BuildRequires:  ros-kinetic-catkin

%description
Yujin Robot's open-source control software

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Jun 17 2016 Jihoon Lee <jihoonl@yujinrobot.com> - 0.8.1-0
- Autogenerated by Bloom

